# Generated by Django 3.2 on 2021-05-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readdataapp', '0002_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_delated',
            field=models.BooleanField(default=False),
        ),
    ]
