# Generated by Django 3.2 on 2021-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readdataapp', '0005_auto_20210507_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='writer',
            new_name='writer_copied',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1620406379.5388343),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.TextField(default=1620406379.5384724),
        ),
    ]
