# Generated by Django 3.2 on 2021-05-07 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readdataapp', '0006_auto_20210507_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1620406531.5840845),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.TextField(default=1620406531.5836785),
        ),
    ]
